"""Add name column to Bakery

Revision ID: 3c0d8dd04475
Revises: a50cde241c4b
Create Date: 2023-10-22 23:00:39.685286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0d8dd04475'
down_revision = 'a50cde241c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baked_goods', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('bakeries', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bakeries', 'name')
    op.drop_column('baked_goods', 'name')
    # ### end Alembic commands ###
